# Generated by Django 4.0 on 2022-01-05 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_alter_post_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rate',
        ),
    ]
